services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postuser
      POSTGRES_PASSWORD: postpass
      POSTGRES_DB: postdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postuser"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.4
    restart: always
    ports:
      - "6378:6379"

  backend:
    build:
      context: ./dummy_site/backend/
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./dummy_site/frontend/
    restart: always
    ports:
      - "8080:80"

volumes:
  pgdata:
